/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VektornyiMassazhRouteImport } from './routes/vektornyi-massazh'
import { Route as VakuumnyiMassazhRouteImport } from './routes/vakuumnyi-massazh'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LimfaticheskiiMassazhRouteImport } from './routes/limfaticheskii-massazh'
import { Route as KlassicheskiiMassazhRouteImport } from './routes/klassicheskii-massazh'
import { Route as KetgutRouteImport } from './routes/ketgut'
import { Route as GirudoterapiyaRouteImport } from './routes/girudoterapiya'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'

const VektornyiMassazhRoute = VektornyiMassazhRouteImport.update({
  id: '/vektornyi-massazh',
  path: '/vektornyi-massazh',
  getParentRoute: () => rootRouteImport,
} as any)
const VakuumnyiMassazhRoute = VakuumnyiMassazhRouteImport.update({
  id: '/vakuumnyi-massazh',
  path: '/vakuumnyi-massazh',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LimfaticheskiiMassazhRoute = LimfaticheskiiMassazhRouteImport.update({
  id: '/limfaticheskii-massazh',
  path: '/limfaticheskii-massazh',
  getParentRoute: () => rootRouteImport,
} as any)
const KlassicheskiiMassazhRoute = KlassicheskiiMassazhRouteImport.update({
  id: '/klassicheskii-massazh',
  path: '/klassicheskii-massazh',
  getParentRoute: () => rootRouteImport,
} as any)
const KetgutRoute = KetgutRouteImport.update({
  id: '/ketgut',
  path: '/ketgut',
  getParentRoute: () => rootRouteImport,
} as any)
const GirudoterapiyaRoute = GirudoterapiyaRouteImport.update({
  id: '/girudoterapiya',
  path: '/girudoterapiya',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/girudoterapiya': typeof GirudoterapiyaRoute
  '/ketgut': typeof KetgutRoute
  '/klassicheskii-massazh': typeof KlassicheskiiMassazhRoute
  '/limfaticheskii-massazh': typeof LimfaticheskiiMassazhRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vakuumnyi-massazh': typeof VakuumnyiMassazhRoute
  '/vektornyi-massazh': typeof VektornyiMassazhRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/girudoterapiya': typeof GirudoterapiyaRoute
  '/ketgut': typeof KetgutRoute
  '/klassicheskii-massazh': typeof KlassicheskiiMassazhRoute
  '/limfaticheskii-massazh': typeof LimfaticheskiiMassazhRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vakuumnyi-massazh': typeof VakuumnyiMassazhRoute
  '/vektornyi-massazh': typeof VektornyiMassazhRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/girudoterapiya': typeof GirudoterapiyaRoute
  '/ketgut': typeof KetgutRoute
  '/klassicheskii-massazh': typeof KlassicheskiiMassazhRoute
  '/limfaticheskii-massazh': typeof LimfaticheskiiMassazhRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vakuumnyi-massazh': typeof VakuumnyiMassazhRoute
  '/vektornyi-massazh': typeof VektornyiMassazhRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/girudoterapiya'
    | '/ketgut'
    | '/klassicheskii-massazh'
    | '/limfaticheskii-massazh'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/vakuumnyi-massazh'
    | '/vektornyi-massazh'
    | '/sitemap/xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/girudoterapiya'
    | '/ketgut'
    | '/klassicheskii-massazh'
    | '/limfaticheskii-massazh'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/vakuumnyi-massazh'
    | '/vektornyi-massazh'
    | '/sitemap/xml'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/girudoterapiya'
    | '/ketgut'
    | '/klassicheskii-massazh'
    | '/limfaticheskii-massazh'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/vakuumnyi-massazh'
    | '/vektornyi-massazh'
    | '/sitemap/xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  GirudoterapiyaRoute: typeof GirudoterapiyaRoute
  KetgutRoute: typeof KetgutRoute
  KlassicheskiiMassazhRoute: typeof KlassicheskiiMassazhRoute
  LimfaticheskiiMassazhRoute: typeof LimfaticheskiiMassazhRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VakuumnyiMassazhRoute: typeof VakuumnyiMassazhRoute
  VektornyiMassazhRoute: typeof VektornyiMassazhRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vektornyi-massazh': {
      id: '/vektornyi-massazh'
      path: '/vektornyi-massazh'
      fullPath: '/vektornyi-massazh'
      preLoaderRoute: typeof VektornyiMassazhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vakuumnyi-massazh': {
      id: '/vakuumnyi-massazh'
      path: '/vakuumnyi-massazh'
      fullPath: '/vakuumnyi-massazh'
      preLoaderRoute: typeof VakuumnyiMassazhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limfaticheskii-massazh': {
      id: '/limfaticheskii-massazh'
      path: '/limfaticheskii-massazh'
      fullPath: '/limfaticheskii-massazh'
      preLoaderRoute: typeof LimfaticheskiiMassazhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klassicheskii-massazh': {
      id: '/klassicheskii-massazh'
      path: '/klassicheskii-massazh'
      fullPath: '/klassicheskii-massazh'
      preLoaderRoute: typeof KlassicheskiiMassazhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ketgut': {
      id: '/ketgut'
      path: '/ketgut'
      fullPath: '/ketgut'
      preLoaderRoute: typeof KetgutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/girudoterapiya': {
      id: '/girudoterapiya'
      path: '/girudoterapiya'
      fullPath: '/girudoterapiya'
      preLoaderRoute: typeof GirudoterapiyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  GirudoterapiyaRoute: GirudoterapiyaRoute,
  KetgutRoute: KetgutRoute,
  KlassicheskiiMassazhRoute: KlassicheskiiMassazhRoute,
  LimfaticheskiiMassazhRoute: LimfaticheskiiMassazhRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VakuumnyiMassazhRoute: VakuumnyiMassazhRoute,
  VektornyiMassazhRoute: VektornyiMassazhRoute,
  SitemapXmlRoute: SitemapXmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
